<script setup lang="ts">
import FunctionModulePage from './FunctionModulePage.vue';
import { commonColumns, makeRowsFromTargets, makeStats, makeTrace, traceColumns } from './functionPageHelpers';
import type { PageContext } from '../types';
defineProps<{ context: PageContext }>();
const targets = ['用户账号管理', '新增用户', '修改用户', '禁用用户', '启用用户', '密码重置', '用户登录记录', '用户所属机构配置', '用户所属科室配置', '用户工作身份配置'];
const rows = makeRowsFromTargets('SYS-USER', '用户管理', '账号身份', targets, '系统管理员', ['新增账号', '修改资料', '停用账号', '启用账号', '重置密码', '查看登录记录', '配置机构', '配置科室', '配置工作身份', '提交复核']);
const cfg = { title: '用户管理', subtitle: '维护用户账号、新增/修改/启停、密码重置、登录记录、所属机构/科室和工作身份配置。', flowText: '员工资料 -> 用户账号 -> 机构科室 -> 工作身份 -> 登录审计', filters: [{ label: '组织', placeholder: '全部组织', type: 'select' as const, options: ['集团', '医院', '院区', '血透中心', '检验科', '药房', '信息科'] }, { label: '账号状态', placeholder: '全部状态', type: 'select' as const, options: ['启用', '禁用', '锁定', '待复核'] }, { label: '工作身份', placeholder: '全部身份', type: 'select' as const, options: ['医生站', '护士站', '导诊台', '检验科工作站', '系统管理'] }, { label: '关键字', placeholder: '姓名、账号、手机号、机构、科室' }], stats: makeStats('用户功能项', rows), rows, columns: commonColumns, primaryAction: '新增/修改用户', primaryDialogTitle: '新增/维护用户账号与身份', primaryFields: [{ label: '登录账号', model: 'loginName' }, { label: '绑定员工', model: 'staff' }, { label: '手机号', model: 'phone' }, { label: '所属机构', model: 'org' }, { label: '所属科室', model: 'dept' }, { label: '工作身份', model: 'identity', type: 'select' as const, options: ['医生站 / 主诊医生', '护士站 / 护理组长', '技师与设备站 / 设备技师', '系统管理 / 系统管理员'] }, { label: '数据范围', model: 'scope', type: 'textarea' as const }], reviewAction: '账号复核', reviewDialogTitle: '用户账号与身份复核', reviewFields: [{ label: '复核结论', model: 'result', type: 'select' as const, options: ['启用', '禁用', '退回', '仅保存草稿'] }, { label: '登录影响', model: 'loginImpact', type: 'textarea' as const }, { label: '意见', model: 'memo', type: 'textarea' as const }], traceTitle: '用户账号审计', traceRows: makeTrace('SYS-USER', '用户管理'), traceColumns, closureTables: 'sys_user / sys_user_org / sys_user_dept / sys_work_identity / sys_login_log / sys_audit_log', closureText: '输入员工资料、机构科室和岗位角色；输出可登录账号、工作身份、登录记录、数据范围和权限控制入口。' };
</script>
<template><FunctionModulePage v-bind="cfg" /></template>
